import { onValue, ref, set, update } from 'firebase/database';
import { firebaseClient, firebaseEnabled } from '../firebase';
import { PLAYER_COLORS, createSnapshot } from '../game/engine';
import type { InputIntent, Player, Room } from '../types';

const memory = new Map<string, Room>();
const code = () => Math.random().toString(36).slice(2, 7).toUpperCase();
export async function identity() { const client = await firebaseClient(); return client?.uid ?? `local-${crypto.randomUUID().slice(0, 8)}`; }
export async function createRoom(name: string) { const uid = await identity(); const roomCode = code(); const player: Player = { id: uid, name, color: PLAYER_COLORS[0], joinedAt: Date.now(), connected: true }; const room: Room = { code: roomCode, hostUid: uid, status: 'lobby', players: { [uid]: player }, createdAt: Date.now() }; const client = await firebaseClient(); if (client) await set(ref(client.db, `rooms/${roomCode}`), room); else memory.set(roomCode, room); return { roomCode, uid }; }
export async function joinRoom(roomCode: string, name: string) { const uid = await identity(); const client = await firebaseClient(); const current = client ? null : memory.get(roomCode); if (!client && !current) throw new Error('That room is not available in local preview. Create a new room first.'); const index = Object.keys(current?.players ?? {}).length; const player: Player = { id: uid, name, color: PLAYER_COLORS[index % PLAYER_COLORS.length], joinedAt: Date.now(), connected: true }; if (client) await update(ref(client.db, `rooms/${roomCode}/players/${uid}`), player); else { current!.players[uid] = player; memory.set(roomCode, current!); } return { roomCode, uid }; }
export async function startRoom(room: Room) { if (Object.keys(room.players).length < 2) throw new Error('Refraction needs at least two players.'); const snapshot = createSnapshot(room.players, Date.now()); const client = await firebaseClient(); if (client) await update(ref(client.db, `rooms/${room.code}`), { status: 'playing', snapshot }); else { room.status = 'playing'; room.snapshot = snapshot; memory.set(room.code, room); } }
export async function sendInput(roomCode: string, uid: string, input: InputIntent) { const client = await firebaseClient(); if (client) await set(ref(client.db, `rooms/${roomCode}/inputs/${uid}`), input); else { const room = memory.get(roomCode); if (room) room.inputs = { ...room.inputs, [uid]: input }; } }
export async function writeSnapshot(roomCode: string, snapshot: Room['snapshot'], status?: Room['status']) { const client = await firebaseClient(); if (client) await update(ref(client.db, `rooms/${roomCode}`), { snapshot, ...(status ? { status } : {}) }); else { const room = memory.get(roomCode); if (room) { room.snapshot = snapshot; if (status) room.status = status; } } }
export function watchRoom(roomCode: string, callback: (room: Room | null) => void) { if (!firebaseEnabled) { const timer = window.setInterval(() => callback(memory.get(roomCode) ?? null), 80); callback(memory.get(roomCode) ?? null); return () => clearInterval(timer); } let stop = () => {}; firebaseClient().then(client => { if (client) stop = onValue(ref(client.db, `rooms/${roomCode}`), snap => callback(snap.val())); }); return () => stop(); }
